version: 2

sources:
  - name: demo
    schema: demo
    freshness:
        warn_after: {count: 2, period: day}
        error_after: {count: 30, period: day}
    quoting:
      database:  "{{ true if target.type != 'redshift' else false }}"
      schema: true
      identifier: true
    loaded_at_field: date

    tables:
      - name: profound_citations
      - name: profound_responses
      - name: profound_sentiment
      - name: profound_visibility
      - name: tv_demo
      - name: paid_search_demo
      - name: calendar_demo